---

- name: Ensure memcached is installed
  apt: 
    name: memcached 
    state: installed

- name: Ensure memcached is started and enabled on boot.
  service: name=memcached state=started enabled=yes

