---


- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no

- name: Ensure httpd is installed
  yum: name=httpd state=installed

- name: Ensure PHP Packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: ['php', 'php-common', 'php-mysql', 'php-gd', 'php-xml', 'php-mbstring', 'php-mcrypt']

- name: Install mysql client
  yum:
    name: mysql
    state: present

- name: Create link for mime.types
  file:
    dest: /etc/httpd/conf/mime.types
    src: /etc/mime.types
    state: link

- name: Copy httpd configuration in place.
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    mode: 0644
  notify: restart httpd

- name: Create DocumentRoot
  file:
    path: "{{ documentroot }}"
    state: directory
    mode: 755
    owner: apache
    group: apache

- name: Copy Virtualhost config
  template:
    src: wordpress.conf.j2
    dest: /etc/httpd/conf.d/wordpress.conf
    mode: 0644
  notify: reload httpd

- name: Remove default virtualhost
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent
  notify: reload httpd

- name: Ensure httpd is started and enabled on boot.
  service: name=httpd state=started enabled=yes

