---

- name: Install apache2
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    ['apache2', 'apache2-utils', 'python-mysqldb']

- name: Install PHP Packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items: 
    ['php5', 'php5-cli', 'php5-gd', 'php5-apcu', 'php5-memcached', 'libapache2-mod-php5', 'php5-mcrypt', 'php5-mysqlnd-ms']

- name: Install mysql client
  apt:
    name: mysql-client
    state: present

- name: Copy config file for session on memcached
  file:
    dest: /etc/php5/mods-available/memcached.ini
    src: memcached.ini
    owner: root
    group: root
    mode: 0644

- name: Copy apache2 configuration in place.
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    mode: 0644
  notify: restart apache2

- name: Create DocumentRoot
  file:
    path: "{{ documentroot }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Copy Virtualhost config
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
    mode: 0644
  notify: reload apache2

- name: Remove default virtualhost
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: reload apache2

- name: Activate Wordpress Virtualhost
  file:
    dest: /etc/apache2/sites-enabled/wordpress.conf
    src: /etc/apache2/sites-available/wordpress.conf
    state: link
  notify: reload apache2

- name: Ensure apache2 is started and enabled on boot.
  service: name=apache2 state=started enabled=yes

