---

- name: Ensure nfs is installed
  yum: name=nfs-utils state=installed

- name: Create dir for NFS Share
  file:
    path: "{{ nfs_share }}"
    state: directory
    mode: 755
    owner: nobody
    group: nobody

- name: Create exports
  copy:
    content: "{{ nfs_share }}  192.168.123.0/24(rw,fsid=0,no_subtree_check,sync,no_root_squash)"
  owner: root
  group: root
  mode: 0644

- name: Ensure nfs is started and enabled on boot.
  service: name=nfs state=started enabled=yes
