---
- name: Configure Time Zone for London
  file: src=/usr/share/zoneinfo/Europe/London dest=/etc/localtime state=link force=yes

- name: Ensure NTP and utilities are installed
  yum: name={{ item }} state=installed
  with_items:
    - ntp
    - ntpdate

- name: Ensure the right configuration is in place
  template: src='ntpd.conf.j2' dest='/etc/ntp.conf'
  notify: restart ntp

- name: Ensure NTP is up and running
  service: name=ntpd state=started enabled=yes
