---



- name: Install wpcli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp-cli
    mode: 0755


- name: Create DocumentRoot
  file:
    path: " {{ documentroot }}"
    state: directory
    mode: 755
    owner: www-data
    group: www-data


- name: Check if Wordpress is Installed
  command: wp-cli core version
  args:
    chdir: " {{ documentroot }}"
  register: result
  ignore_errors: True


- name: Download Wordpress core
  command: wp-cli core download
  args:
    chdir: " {{ documentroot }}"
  when: result|failed

- name: Create the wp-config file
  command: wp-cli core config --dbname={{ db.name }} --dbuser={{ db.user }} --dbpass={{ db.pass }}
  args:
    chdir: " {{ documentroot }}"
  when: result|failed


- name: create database
  command: wp-cli db create
  args:
    chdir: " {{ documentroot }}"
  when: result|failed

- name: Install WordPress
  command: wp-cli core install --url=http://localhost --title="{{ blog.title }}"  --admin_user="{{ blog.admin }}" --admin_password="{{ blog.pass }}" --admin_email="{{ blog.email }}"
  args:
    chdir: " {{ documentroot }}"
  when: result|failed

- name: Ensure nfs-utils is installed
  yum: name=nfs-utils state=installed
  
- name: Mount nfs
  mount: 
    name:{{ documentroot }}/wp-content/uploads
    src: {{hostvars[groups['be'][0]]['ansible_eth0']['ipv4']['address']}}:/{{ nfs_share }} 
    fstype: nfs 
    opts: defaults,nobootwait 
    dump: 0 
    passno: 2 
    state: mounted



