---

- name: Install wpcli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp-cli
    mode: 0755


- name: Check if Wordpress is Installed
  command: /usr/local/bin/wp-cli core version
  args:
    chdir: "{{ documentroot }}"
  register: result
  ignore_errors: True


- name: Download Wordpress core
  command: /usr/local/bin/wp-cli core download
  args:
    chdir: "{{ documentroot }}"
  when: result|failed

- name: Check if wp-config already exist
  stat: 
    path: "{{ documentroot }}/wp-config.php"
  register: register

- name: Create the wp-config file
  command: "/usr/local/bin/wp-cli core config --dbname={{ db.name }} --dbuser={{ db.user }} --dbpass={{ db.pass }} --dbhost=be"
  args:
    chdir: "{{ documentroot }}"
  when: register.stat.exists == False

- name: Ensure nfs-utils is installed
  yum: name=nfs-utils state=installed

- name: Create uploads 
  file: 
    path: "{{ documentroot }}/wp-content/uploads"
    state: directory

- name: create database
  command: /usr/local/bin/wp-cli db create
  args:
    chdir: "{{ documentroot }}"
  run_once: true
  delegate_to: wp1

- name: Install WordPress
  command: /usr/local/bin/wp-cli core install --url=http://localhost --title="{{ blog.title }}"  --admin_user="{{ blog.admin }}" --admin_password="{{ blog.pass }}" --admin_email="{{ blog.email }}"
  args:
    chdir: "{{ documentroot }}"
  run_once: true
  delegate_to: wp1


- name: Save the script to create a few posts
  template:
    src: create_post.sh.j2
    dest: '/usr/local/bin/create_post.sh'
    mode: 0755

- name: create posts
  command: "/usr/local/bin/create_post.sh"
  run_once: true
  delegate_to: wp1
