---

- name: Install mysql
  yum:
    name: "{{ item }}"
    state: present 
  with_items:
      - mysql
      - mysql-server
      - MySQL-python

- name: Ensure MySQL is up and running
  service: name=mysqld state=started enabled=yes


- name: Create a database for Wordpress
  mysql_db:
    name: "{{ db.name }}"
    state: present

- name: Create database user
  mysql_user: 
    user: "{{ db.user }}"
    password: "{{ db.pass }}"
    host: "%"
    priv: "{{ db.name }}.*:ALL" 
    state: present

- name: Remove anonyous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
