---
# This playbook contains common plays that will be run on all nodes.

- hosts: all
  become: yes
  gather_facts: no

  roles:

- hosts: lb
  become: yes
  gather_facts: no

  roles:
    - haproxy
